### ISSUE TITLE
Вспомогательная Map в Dictionary

### ISSUE THREAD

**Issue by Blackmorse** [VladAver87/LearnEn#4]
Попробуй вспомнить то, когда я говорил про принцип "черного ящика"
Класс должен предоставлять удобные методы для общения с ним, но про внутреннюю реализацию класса знать снаружи никто не должен
Мапа supportDict в Dictionary задействуется снаружи, хотя это чисто внутренний механизм Dictionary.
Попробуй переработать код так, чтобы "сокрыть" supportDict внутри Dictionary

**Comment by VladAver87** [comment]
то есть метод addToSupportDict тоже требует переработки?
